### ISSUE TITLE
Unknown CUDA error

### ISSUE THREAD

**Issue by davesullivan41** [georgedimitriadis/spikesorting_tsne#1]
I'm attempting to run TSNE on a machine in the cloud, but I'm having trouble. This machine has successfully run tensorflow operations before, so I know the Nvidia drivers are set up properly. I'm running Nvidia Driver Version: 390.30, numba version 0.39.0, and pyculib 1.0.2, all on a Tesla K80. Do you have any insight into why this error would be happening? Thanks in advance!

```
LOADING UP THE GPU
Loading matrix time:  0.010 s
ITERATION NUMBER: 1
Making the dot products Time: 0.008 s
Summing the dot products on the GPU Time: 0.178 s
cuBLAS gemm Time: 0.174 s
     Number of sorting segments = 6
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/spikesorting_tsne/gpu.py", line 189, in _segment_sort_transposed_distances_get_knns
    sorting.segmented_sort(keys=keys, vals=values, segments=segments)
  File "/opt/conda/lib/python3.6/site-packages/pyculib/sorting/segsort.py", line 115, in segmented_sort
    _segmentedsort(d_keys, d_vals, d_segments, stream)
  File "/opt/conda/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.6/site-packages/pyculib/sorting/segsort.py", line 84, in _autodevice
    dptr.copy_to_host(ary, stream=stream)
  File "/opt/conda/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/opt/conda/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py", line 241, in copy_to_host
    _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
  File "/opt/conda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 1606, in device_to_host
    fn(host_pointer(dst), device_pointer(src), size, *varargs)
  File "/opt/conda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/opt/conda/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemcpyDtoH results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/spikesorting_tsne/gpu.py", line 294, in calculate_knn_distances
    number_of_sorts=number_of_sorts, verbose=verbose)
  File "/opt/conda/lib/python3.6/site-packages/spikesorting_tsne/gpu.py", line 198, in _segment_sort_transposed_distances_get_knns
    print('     Sorted {} of {} segments of this iteration'.format(i, p.shape[0] - 1))
  File "/opt/conda/lib/python3.6/site-packages/spikesorting_tsne/stopwatch.py", line 82, in __exit__
    raise type
TypeError: __init__() missing 2 required positional arguments: 'code' and 'msg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/spikesorting_tsne/gpu.py", line 302, in calculate_knn_distances
    ' ITERATIONS')
  File "/opt/conda/lib/python3.6/site-packages/spikesorting_tsne/stopwatch.py", line 82, in __exit__
    raise type
TypeError
```

**Comment by davesullivan41** [comment]
I tested it on another machine, with the same driver and package numbers, but with a different GPU. 
The following code produces the error below, which is sufficiently similar to the original error that I suspect the root cause is the same.

```
from spikesorting_tsne import tsne as TSNE
import numpy as np

samples = np.random.random_sample((10000, 10))


theta = 0.4
eta = 200.0
num_dims = 2
perplexity = 100
iterations = 1000
random_seed = 1
verbose = 2
tsne = TSNE.t_sne(samples=samples, files_dir='./', num_dims=num_dims,
                  perplexity=perplexity, theta=theta, eta=eta, iterations=iterations, random_seed=random_seed,
                  verbose=verbose)
```


```
LOADING UP THE GPU
Loading matrix time:  1.109 s
ITERATION NUMBER: 1
Making the dot products Time: 0.004 s
Summing the dot products on the GPU Time: 0.184 s
cuBLAS gemm Time: 0.650 s
     Number of sorting segments = 6
---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in _segment_sort_transposed_distances_get_knns(num_of_neighbours, distances_on_gpu, number_of_sorts, verbose)
    188             # 4. Do the segmented sort
--> 189             sorting.segmented_sort(keys=keys, vals=values, segments=segments)
    190 

~/anaconda3/lib/python3.6/site-packages/pyculib/sorting/segsort.py in segmented_sort(keys, vals, segments, stream)
    114             d_segments, _ = auto_device(segments, stream=stream)
--> 115             _segmentedsort(d_keys, d_vals, d_segments, stream)
    116 

~/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:

~/anaconda3/lib/python3.6/site-packages/pyculib/sorting/segsort.py in _autodevice(ary, stream)
     83         if conv:
---> 84             dptr.copy_to_host(ary, stream=stream)
     85     else:

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    211         get_context()
--> 212         return fn(*args, **kws)
    213 

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py in copy_to_host(self, ary, stream)
    251         if self.alloc_size != 0:
--> 252             _driver.device_to_host(hostary, self, self.alloc_size, stream=stream)
    253 

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in device_to_host(dst, src, size, stream)
   1775 
-> 1776     fn(host_pointer(dst), device_pointer(src), size, *varargs)
   1777 

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    287             retcode = libfn(*args)
--> 288             self._check_error(fname, retcode)
    289         return safe_cuda_api_call

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    322                     raise CudaDriverError("CUDA initialized before forking")
--> 323             raise CudaAPIError(retcode, msg)
    324 

CudaAPIError: [719] Call to cuMemcpyDtoH results in CUDA_ERROR_LAUNCH_FAILED

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in calculate_knn_distances(samples_matrix, perplexity, verbose)
    293                                                                 distances_on_gpu=distances_on_gpu,
--> 294                                                                 number_of_sorts=number_of_sorts, verbose=verbose)
    295 

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in _segment_sort_transposed_distances_get_knns(num_of_neighbours, distances_on_gpu, number_of_sorts, verbose)
    197             if verbose:
--> 198                 print('     Sorted {} of {} segments of this iteration'.format(i, p.shape[0] - 1))
    199 

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/stopwatch.py in __exit__(self, type, value, traceback)
     81         if type:
---> 82             raise type

TypeError: __init__() missing 2 required positional arguments: 'code' and 'msg'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in calculate_knn_distances(samples_matrix, perplexity, verbose)
    301                     print('FINISHED CALCULATING ' + str(iteration + 1) + ' OF ' + str(number_of_iters) +
--> 302                           ' ITERATIONS')
    303 

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/stopwatch.py in __exit__(self, type, value, traceback)
     81         if type:
---> 82             raise type

TypeError: 

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-3-61df54fd3da1> in <module>()
     14 tsne = TSNE.t_sne(samples=samples, files_dir='./', num_dims=num_dims,
     15                   perplexity=perplexity, theta=theta, eta=eta, iterations=iterations, random_seed=random_seed,
---> 16                   verbose=verbose)

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/tsne.py in t_sne(samples, files_dir, exe_dir, num_dims, perplexity, theta, eta, exageration, iterations, random_seed, verbose)
     89     data /= data.max()
     90     closest_indices_in_hd, closest_distances_in_hd = \
---> 91         gpu.calculate_knn_distances(samples_matrix=data, perplexity=perplexity, verbose=True)
     92 
     93     io.save_data_for_barneshut(files_dir, closest_distances_in_hd, closest_indices_in_hd, num_of_dims=num_dims,

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in calculate_knn_distances(samples_matrix, perplexity, verbose)
    303 
    304             if verbose:
--> 305                 print("Spend Time: {0:.3f} s".format(outside_stopwatch.time_elapsed))
    306 
    307     return closest_indices, np.sqrt(np.abs(closest_distances))

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/stopwatch.py in __exit__(self, type, value, traceback)
     80         self.stop()
     81         if type:
---> 82             raise type
```

**Comment by georgedimitriadis** [comment]
Hello davesullivan41

I haven't got a clue what the problem might be. I am running my system on a desktop with pyculib 1.0.2, numba 0.33.0 and 388.13 NVIDIA and it works fine. 
I have checked that the code works both in Windows and in Linux (on a Mint). 

But all the machines I have tested the code are desktops, not on the cloud.

Would you mind adding some prints in the code in the gpu.py in the calculate_knn_distances() so that I can see the n, m, number_of_iters, available_gpu_mem and also some prints in the _segment_sort_transposed_distances_get_knns() to get the m, n and delta_n?

Thanks

George

**Comment by davesullivan41** [comment]
I'm going to add those print statements and follow up, but I downgraded numba to 0.33.0 and had the same issue.

**Comment by davesullivan41** [comment]
Here are the printouts for `calculate_knn_distances()`:

```
m: 10000
n: 31307
available_gpu_mem: 1252261888.0
number_of_iters: 1
```

and here they are for _segment..., after which it fails
```
m: 10000
n: 10000
delta_n: 2000
```
UPDATED to add _segment printouts, didn't have them in an earlier version of htis comment because of a mistake on my end

**Comment by davesullivan41** [comment]
What version of the cudatoolkit are you running? I have been running with 9, but I've read on the internet that there are some issues with numba and CUDA 9.0+

**Comment by davesullivan41** [comment]
On second look, it looks like I'm actually using cudatoolkit 7.5. I forgot I had downgraded in this environment specifically to get numba working. I tried cudatoolkit 9.0, but numba just wouldn't even start up.

**Comment by georgedimitriadis** [comment]
I am using 8.0. Is it possible for you to downgrade to 8.0 and have a go? I have never used numba with 7.5 (or 9.0) and all of the code was developed in 8.0. All of the machines that I have tested the code on have been using 8.0

George

**Comment by davesullivan41** [comment]
Downgraded to cudatoolkit 8.0, and I get the same error now, but at a different location.
```
CudaAPIError                              Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in calculate_knn_distances(samples_matrix, perplexity, verbose)
    240 
--> 241         available_gpu_mem = _get_required_gpu_memory()
    242 

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in _get_required_gpu_memory()
    210     """
--> 211     gpu_mem = cuda.current_context().get_memory_info()
    212     available_gpu_mem = 0.5 * gpu_mem[0]

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in get_memory_info(self)
    593         total = c_size_t()
--> 594         driver.cuMemGetInfo(byref(free), byref(total))
    595         return _MemoryInfo(free=free.value, total=total.value)

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    287             retcode = libfn(*args)
--> 288             self._check_error(fname, retcode)
    289         return safe_cuda_api_call

~/anaconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    322                     raise CudaDriverError("CUDA initialized before forking")
--> 323             raise CudaAPIError(retcode, msg)
    324 

CudaAPIError: [719] Call to cuMemGetInfo results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-fca4c9dbb179> in <module>()
     14 tsne = TSNE.t_sne(samples=samples, files_dir='./', num_dims=num_dims,
     15                   perplexity=perplexity, theta=theta, eta=eta, iterations=iterations, random_seed=random_seed,
---> 16                   verbose=verbose)

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/tsne.py in t_sne(samples, files_dir, exe_dir, num_dims, perplexity, theta, eta, exageration, iterations, random_seed, verbose)
     89     data /= data.max()
     90     closest_indices_in_hd, closest_distances_in_hd = \
---> 91         gpu.calculate_knn_distances(samples_matrix=data, perplexity=perplexity, verbose=True)
     92 
     93     io.save_data_for_barneshut(files_dir, closest_distances_in_hd, closest_indices_in_hd, num_of_dims=num_dims,

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/gpu.py in calculate_knn_distances(samples_matrix, perplexity, verbose)
    304 
    305             if verbose:
--> 306                 print("Spend Time: {0:.3f} s".format(outside_stopwatch.time_elapsed))
    307 
    308     return closest_indices, np.sqrt(np.abs(closest_distances))

~/anaconda3/lib/python3.6/site-packages/spikesorting_tsne/stopwatch.py in __exit__(self, type, value, traceback)
     80         self.stop()
     81         if type:
---> 82             raise type

TypeError: __init__() missing 2 required positional arguments: 'code' and 'msg'
```

**Comment by davesullivan41** [comment]
I'm not sure if you've worked with Docker before, but the following image run with nvidia-docker produces the same errors I've been seeing on the 'segmented_sort' function: 

```
FROM nvidia/cuda:8.0-devel

RUN apt update -y && \
        apt install -y libgl1-mesa-glx apt-transport-https curl locales git wget libgsl-dev bzip2

ENV PATH /opt/conda/bin:$PATH
RUN wget --quiet https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

RUN conda update conda
RUN conda install numba=0.37.0 pyculib cudatoolkit=8.0 && \
        conda install -c georgedimitriadis spikesorting_tsne
WORKDIR /app

CMD python tsne_test.py
```

I have a few more different GPU machines I can try this on (in the cloud and local), and I will let you know the results. Hopefully it's as simple as a version mismatch that can be added to the install requirements.

Also, in case it wasn't obvious 'tsne_test.py' has the code found in my initial post.

**Comment by georgedimitriadis** [comment]
Hello,

I am really baffled (as usually by CUDA errors). It seems that all the errors have to do with CUDA failing to see the current context.

Could it be that the way the GPU is setup in your server needs to have its stream/context specified (something that I do not do because I assume  only a single GPU). 

Could you run the code in a machine that you know has only a single GPU?

There is also the difference between GTX and Tesla. I have only tried in GTX. It might be that Tesla required extra stuff to get their context (or that numba is not happy with them).

George

**Comment by davesullivan41** [comment]
Hey George, 
This machine only has 1 GPU. I've been attempting to get CUDA set up on my local machine (with a GTX 1050), but I made the mistake of updating to Ubuntu 18.04, which isn't yet supported by CUDA. 

I think you are right about the context issues, it seems to consistently fail when trying to move values between the host and the device. I'm hoping some careful editing of how context is handled will fix the issue. I'm going to spend my morning playing around with this, and I'll keep you posted. 

I'm not sure if you've spent any time with CUDA-MEMCHECK, but the following is what I see when I run that on the code I sent in my initial post. (There's about 80 of these). 
```
========= CUDA-MEMCHECK
========= Invalid __shared__ write of size 1
=========     at 0x000001f0 in void mgpu::KernelSegBlocksortIndices<mgpu::LaunchBoxVT<int=128, int=11, int=0, int=128, int=7, int=0, int=128, int=7, int=0>, bool=1, bool=1, float*, unsigned int*, float*, unsigned int*, mgpu::less<float>>(int=128, int=7, int, int const *, int const , int=0, int=128, int*, int=7)
=========     by thread (5,0,0) in block (91,0,0)
=========     Address 0xfffec180 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so (cuLaunchKernel + 0x2cd) [0x22b12d]
=========     Host Frame:/anaconda/envs/tsne/lib/pyculib_segsort.so [0x301e1]
=========     Host Frame:/anaconda/envs/tsne/lib/pyculib_segsort.so [0x4a9f3]
=========     Host Frame:/anaconda/envs/tsne/lib/pyculib_segsort.so (_ZN4mgpu23SegSortPairsFromIndicesIfjNS_4lessIfEEEEvPT_PT0_iPKiiRNS_11CudaContextET1_b + 0xaec) [0x1552c]
=========     Host Frame:/anaconda/envs/tsne/lib/pyculib_segsort.so (segsortpairs_float32 + 0x4f) [0xdfef]
=========     Host Frame:/anaconda/envs/tsne/lib/python3.6/lib-dynload/../../libffi.so.6 (ffi_call_unix64 + 0x4c) [0x5ec0]
=========     Host Frame:/anaconda/envs/tsne/lib/python3.6/lib-dynload/../../libffi.so.6 (ffi_call + 0x22d) [0x587d]
=========     Host Frame:/anaconda/envs/tsne/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so (_ctypes_callproc + 0x2ce) [0x11dae]
=========     Host Frame:/anaconda/envs/tsne/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so [0x12708]
=========     Host Frame:python (_PyObject_FastCallDict + 0x8b) [0x10fbcb]
=========     Host Frame:python [0x19cf4e]
```
-Dave

**Comment by davesullivan41** [comment]
Hey George, 

I swapped out the `segmented_sort` function in gpu.py for the RadixSort, and it now seems to do the sorting without issue. So it must be some sort of issue with the way the segmented sort manages memory. However, now I'm getting the following error (which I suspect is because I've been mucking about in your code too much):

```
Spend Time: 4.868 s
Read the 1000 x 301 data matrix successfully!
Using random seed: 1
Using no_dims = 2, perplexity = 100, learning rate = 200.000000, exageration = 12.000000 and theta = 0.400000

Computing Gaussian perplexities...

Symmetrizing sparce perplexity matirx...
Traceback (most recent call last):
  File "tsne_test.py", line 16, in <module>
    verbose=verbose)
  File "/anaconda/envs/tsne/lib/python3.6/site-packages/spikesorting_tsne/tsne.py", line 101, in t_sne
    run_executable(exe_file, files_dir, verbose)
  File "/anaconda/envs/tsne/lib/python3.6/site-packages/spikesorting_tsne/tsne.py", line 53, in run_executable
    'refer to the t_sne output for further details')
AssertionError: ERROR: Call to Barnes_Hut exited with a non-zero return code exit status, please refer to the t_sne output for further details
```

Any insights? I set the verbosity on the tsne call to '3', and still dont' get anythign beyond that error. Did I mess something up with installing the Barnes_Hut binary?

-Dave

**Comment by davesullivan41** [comment]
It looks like the return code is `-11`. Do you know what that means?

**Comment by georgedimitriadis** [comment]
Hello,

Thanks for keep trying with this. 

I do not remember exactly what the RadixSort does but I would be surprised if it gave the exact same results without some serious tweaking. 

The Barnes_Hut.exe seems to break very early on, which means that the data given to it do not make sense. At the point it breaks you won't get any other feedback even with verbose=3. I do not remember if the errors generated in the exe will propagate to the python's command line? Are you running the code with Docker? If yes try and run it straight from a python terminal and see if you get errors from the C++ code.

None the less you shouldn't need to change the segment_sort. I seem to remember that I chose this over RadixSort for a reason (I do not remeber what though, it's been some time). 

I had a problem running a python package some time ago (in my windows system) that was developed in a Linux system. The problem (which took a month to solve) was that Linux assumed the ints to be 64 bits while windows assumed 32 bits. So arrays were horribly malformed. 

In the _segment_sort_transposed_distances_get_knns() the segmented_sort needs 3 arrays. The keys, the values and the segments. The keys have to be float32 because that is how they are defined in calculate_knn_distances (line 270). But the other two arrays are ints that I do not define explicitly. They are int32 though because in windows the line p = np.append(np.arange(0, n, int(n / number_of_sorts)), n) generates an array of int32 and then the values and segments are calculated based on the p array thus end up being int32. If your Linux system is doing something different to my Widnows system with those that might break the copying over to gpu memory. Do you want and try and define the values and the segments as int32 (you can do it with a dtype parameter in the np.ascontiguousarray functions).

To be honest I cannot think of what else can be wrong. I have tried the code on two windows machines and one Linux, bu the Linux was a Windows subsystem. I have been told this runs identical to Linux but I will happily believe that this is not the case. I will give the code to a collegue of mine to run on a full Linux machine and see what happens.

George
George

**Comment by davesullivan41** [comment]
Ah, thanks for the insight, I was fiddling around with data types and memory allocation and just couldn't quite get it right. I should have a chance tomorrow to give that a try, and I'll let you know. 

Dave

**Comment by davesullivan41** [comment]
Specifying the data types worked! I'll send a PR your way with that change.
